spring.application.name=trading

spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=trading
spring.data.mongodb.auto-index-creation=true

stripe.api.key=${STRIPE_SECRET_KEY}
razorpay.api.key=${RAZORPAY_KEY}
razorpay.api.secret=${RAZORPAY_SECRET}

cryptocompare.key=${CRYPTOCOMPARE_KEY}
